,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,user,labels,state,locked,assignee,assignees,milestone,comments,created_at,updated_at,closed_at,author_association,active_lock_reason,body,reactions,timeline_url,performed_via_github_app,draft,pull_request
0,https://api.github.com/repos/pandas-dev/pandas/issues/44705,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44705/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44705/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44705/events,https://github.com/pandas-dev/pandas/issues/44705,1068598638,I_kwDOAA0YD84_sYVu,44705,BUG: Python's date and time objects do not roundtrip with JSON orient='table',"{'login': 'jmg-duarte', 'id': 15343819, 'node_id': 'MDQ6VXNlcjE1MzQzODE5', 'avatar_url': 'https://avatars.githubusercontent.com/u/15343819?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jmg-duarte', 'html_url': 'https://github.com/jmg-duarte', 'followers_url': 'https://api.github.com/users/jmg-duarte/followers', 'following_url': 'https://api.github.com/users/jmg-duarte/following{/other_user}', 'gists_url': 'https://api.github.com/users/jmg-duarte/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jmg-duarte/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jmg-duarte/subscriptions', 'organizations_url': 'https://api.github.com/users/jmg-duarte/orgs', 'repos_url': 'https://api.github.com/users/jmg-duarte/repos', 'events_url': 'https://api.github.com/users/jmg-duarte/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jmg-duarte/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 49379259, 'node_id': 'MDU6TGFiZWw0OTM3OTI1OQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20JSON', 'name': 'IO JSON', 'color': '207de5', 'default': False, 'description': 'read_json, to_json, json_normalize'}]",open,False,,[],,7,2021-12-01T16:12:45Z,2021-12-01T17:26:37Z,,NONE,,"### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.


### Reproducible Example

```python
import datetime as dt
import pandas as pd

date_df = pd.DataFrame({""d"": [dt.date.today()]})
date_df_json = date_df.to_json(orient='table')
date_df_back = pd.read_json(date_df_json, orient='table')
assert date_df.equals(date_df_back) # fails

time_df = pd.DataFrame({""t"": [dt.time()]})
time_df_json = time_df.to_json(orient='table')
time_df_back = pd.read_json(time_df_json, orient='table')
assert time_df.equals(time_df_back) # fails
```


### Issue Description

`datetime.date` and `datetime.time` objects are not serialized correctly when getting converted to and from JSON.

The main issue *seems to be* the lack of information when (de)serializing the JSON DataFrame. 
Given that pandas makes use of the the Table Schema from Frictionless Standards, it should support both, as made evident by:
- https://specs.frictionlessdata.io//table-schema/#date 
- https://specs.frictionlessdata.io//table-schema/#time.

NOTE: This has been discussed in #20612 and #32037.

### Expected Behavior

Both types make the roundtrip.

### Installed Versions

<details><pre><code>INSTALLED VERSIONS
------------------
commit           : 73c68257545b5f8530b7044f56647bd2db92e2ba
python           : 3.8.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.3.3
numpy            : 1.21.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.1.1
setuptools       : 56.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.29.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 2021.11.0
fastparquet      : 0.7.1
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 6.0.1
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None</code></pre></details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44705/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44705/timeline,,,
1,https://api.github.com/repos/pandas-dev/pandas/issues/44703,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44703/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44703/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44703/events,https://github.com/pandas-dev/pandas/issues/44703,1068156482,I_kwDOAA0YD84_qsZC,44703,BUG: Can't use iloc to set a subset of a dataframe to a two-dimensional categorical data array.,"{'login': 'mvashishtha', 'id': 10712109, 'node_id': 'MDQ6VXNlcjEwNzEyMTA5', 'avatar_url': 'https://avatars.githubusercontent.com/u/10712109?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mvashishtha', 'html_url': 'https://github.com/mvashishtha', 'followers_url': 'https://api.github.com/users/mvashishtha/followers', 'following_url': 'https://api.github.com/users/mvashishtha/following{/other_user}', 'gists_url': 'https://api.github.com/users/mvashishtha/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mvashishtha/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mvashishtha/subscriptions', 'organizations_url': 'https://api.github.com/users/mvashishtha/orgs', 'repos_url': 'https://api.github.com/users/mvashishtha/repos', 'events_url': 'https://api.github.com/users/mvashishtha/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mvashishtha/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2021-12-01T09:17:55Z,2021-12-01T09:18:48Z,,NONE,,"### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.


### Reproducible Example

```python
import pandas as pd
from numpy import array
df = pd.DataFrame({""status"": [""a"", ""b"", ""c""]},  dtype=""category"")
df.iloc[array([0, 1]), array([0])] = array([['a'], ['a']])
```


### Issue Description

I can't use `iloc` set a subset of a dataframe to a two-dimensional categorical data array. The reproducible example gives this stack trace:

<details>
  <summary>Click to see stack trace</summary>
  
  ```
TypeError                                 Traceback (most recent call last)
<ipython-input-10-d6ae260d158c> in <module>
      2 from numpy import array
      3 df = pd.DataFrame({""status"": [""a"", ""b"", ""c""]},  dtype=""category"")
----> 4 df.iloc[array([0, 1]), array([0])] = array([['a'], ['a']])

~/pandas/pandas/core/indexing.py in __setitem__(self, key, value)
    708
    709         iloc = self if self.name == ""iloc"" else self.obj.iloc
--> 710         iloc._setitem_with_indexer(indexer, value, self.name)
    711
    712     def _validate_key(self, key, axis: int):

~/pandas/pandas/core/indexing.py in _setitem_with_indexer(self, indexer, value, name)
   1671             self._setitem_with_indexer_split_path(indexer, value, name)
   1672         else:
-> 1673             self._setitem_single_block(indexer, value, name)
   1674
   1675     def _setitem_with_indexer_split_path(self, indexer, value, name: str):

~/pandas/pandas/core/indexing.py in _setitem_single_block(self, indexer, value, name)
   1919
   1920         # actually do the set
-> 1921         self.obj._mgr = self.obj._mgr.setitem(indexer=indexer, value=value)
   1922         self.obj._maybe_update_cacher(clear=True, inplace=True)
   1923

~/pandas/pandas/core/internals/managers.py in setitem(self, indexer, value)
    335         For SingleBlockManager, this backs s[indexer] = value
    336         """"""
--> 337         return self.apply(""setitem"", indexer=indexer, value=value)
    338
    339     def putmask(self, mask, new, align: bool = True):

~/pandas/pandas/core/internals/managers.py in apply(self, f, align_keys, ignore_failures, **kwargs)
    302                     applied = b.apply(f, **kwargs)
    303                 else:
--> 304                     applied = getattr(b, f)(**kwargs)
    305             except (TypeError, NotImplementedError):
    306                 if not ignore_failures:

~/pandas/pandas/core/internals/blocks.py in setitem(self, indexer, value)
   1513
   1514         check_setitem_lengths(indexer, value, self.values)
-> 1515         self.values[indexer] = value
   1516         return self
   1517

~/pandas/pandas/core/arrays/_mixins.py in __setitem__(self, key, value)
    249     def __setitem__(self, key, value):
    250         key = check_array_indexer(self, key)
--> 251         value = self._validate_setitem_value(value)
    252         self._ndarray[key] = value
    253

~/pandas/pandas/core/arrays/categorical.py in _validate_setitem_value(self, value)
   1445         if not is_hashable(value):
   1446             # wrap scalars and hashable-listlikes in list
-> 1447             return self._validate_listlike(value)
   1448         else:
   1449             return self._validate_scalar(value)

~/pandas/pandas/core/arrays/categorical.py in _validate_listlike(self, value)
   2080         # something to np.nan
   2081         if len(to_add) and not isna(to_add).all():
-> 2082             raise TypeError(
   2083                 ""Cannot setitem on a Categorical with a new ""
   2084                 ""category, set the categories first""

TypeError: Cannot setitem on a Categorical with a new category, set the categories first
  ```
</details>

The problem seems to only come up when the dataframe has a single column. If I just add another column to the dataframe, it works:

```python
import pandas as pd
from numpy import array
df = pd.DataFrame({""status"": [""a"", ""b"", ""c""], ""status2"": [""d"", ""e"", ""f""]},  dtype=""category"")
df.iloc[array([0, 1]), array([0])] = array([['a'], ['a']])
```


### Expected Behavior

I expect to see that the dataframe has the `status` column set to ""a"" for the first two rows.

```
status
0      a   
1      a   
2      c    
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4e139f69ff353f79c183fddda9110a8ed2ff6a41
python           : 3.8.12.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.0.dev0+1273.g4e139f69ff
numpy            : 1.21.4
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 59.4.0
Cython           : 0.29.24
pytest           : 6.2.5
hypothesis       : 6.29.0
sphinx           : 4.3.1
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : 4.6.4
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.30.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fsspec           : 2021.11.0
fastparquet      : 0.7.2
gcsfs            : 2021.11.0
matplotlib       : 3.5.0
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 6.0.1
pyxlsb           : None
s3fs             : 2021.11.0
scipy            : 1.7.3
sqlalchemy       : 1.4.27
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : 0.18.2
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.53.1


</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44703/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44703/timeline,,,
2,https://api.github.com/repos/pandas-dev/pandas/issues/44702,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44702/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44702/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44702/events,https://github.com/pandas-dev/pandas/pull/44702,1068087509,PR_kwDOAA0YD84vO3Z3,44702,DOC: fix examples in Timestamp functions,"{'login': 'valentinoli', 'id': 23453691, 'node_id': 'MDQ6VXNlcjIzNDUzNjkx', 'avatar_url': 'https://avatars.githubusercontent.com/u/23453691?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/valentinoli', 'html_url': 'https://github.com/valentinoli', 'followers_url': 'https://api.github.com/users/valentinoli/followers', 'following_url': 'https://api.github.com/users/valentinoli/following{/other_user}', 'gists_url': 'https://api.github.com/users/valentinoli/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/valentinoli/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/valentinoli/subscriptions', 'organizations_url': 'https://api.github.com/users/valentinoli/orgs', 'repos_url': 'https://api.github.com/users/valentinoli/repos', 'events_url': 'https://api.github.com/users/valentinoli/events{/privacy}', 'received_events_url': 'https://api.github.com/users/valentinoli/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2021-12-01T08:06:23Z,2021-12-01T08:06:23Z,,NONE,,"- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

I tried to create a new issue with the issue template 2 times but I got this error each time

![image](https://user-images.githubusercontent.com/23453691/144195459-541b63df-e84f-4a9f-9a90-855b8e68dbce.png)

Anyway, these changes are very small so perhaps there is no need to create an issue. I didn't run any tests since I made the changes through GitHub and did not clone the project locally.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44702/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44702/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/44702', 'html_url': 'https://github.com/pandas-dev/pandas/pull/44702', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/44702.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/44702.patch', 'merged_at': None}"
3,https://api.github.com/repos/pandas-dev/pandas/issues/44700,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44700/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44700/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44700/events,https://github.com/pandas-dev/pandas/pull/44700,1068008145,PR_kwDOAA0YD84vOmnx,44700,TST: Use IPython instance fixture to avoid file leak,"{'login': 'mroeschke', 'id': 10647082, 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mroeschke', 'html_url': 'https://github.com/mroeschke', 'followers_url': 'https://api.github.com/users/mroeschke/followers', 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}', 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions', 'organizations_url': 'https://api.github.com/users/mroeschke/orgs', 'repos_url': 'https://api.github.com/users/mroeschke/repos', 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mroeschke/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2021-12-01T06:17:03Z,2021-12-01T16:44:14Z,,MEMBER,,"- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them

xref https://github.com/pandas-dev/pandas/pull/44634, https://github.com/pandas-dev/pandas/pull/35836

Probably should see if anything can be done on the iPython side.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44700/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44700/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/44700', 'html_url': 'https://github.com/pandas-dev/pandas/pull/44700', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/44700.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/44700.patch', 'merged_at': None}"
4,https://api.github.com/repos/pandas-dev/pandas/issues/44699,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44699/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44699/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44699/events,https://github.com/pandas-dev/pandas/pull/44699,1067963885,PR_kwDOAA0YD84vOdLb,44699,TST: de-duplicate fixtures,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2021-12-01T05:02:04Z,2021-12-01T05:02:04Z,,MEMBER,,"- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44699/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44699/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/44699', 'html_url': 'https://github.com/pandas-dev/pandas/pull/44699', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/44699.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/44699.patch', 'merged_at': None}"
5,https://api.github.com/repos/pandas-dev/pandas/issues/44697,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44697/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44697/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44697/events,https://github.com/pandas-dev/pandas/pull/44697,1067793194,PR_kwDOAA0YD84vN5GV,44697,BUG: Series.where with incompatible NA value,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2021-12-01T00:04:28Z,2021-12-01T02:55:58Z,,MEMBER,,"- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

Sits on top of #44514 (i.e. merge that first)

With this, can follow up to share where methods between Block subclasses.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44697/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44697/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/44697', 'html_url': 'https://github.com/pandas-dev/pandas/pull/44697', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/44697.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/44697.patch', 'merged_at': None}"
6,https://api.github.com/repos/pandas-dev/pandas/issues/44696,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44696/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44696/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44696/events,https://github.com/pandas-dev/pandas/issues/44696,1067781117,I_kwDOAA0YD84_pQv9,44696,BUG: Apply ewm to GroupBy object results in duplicate index columns,"{'login': 'matteosantama', 'id': 13473688, 'node_id': 'MDQ6VXNlcjEzNDczNjg4', 'avatar_url': 'https://avatars.githubusercontent.com/u/13473688?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/matteosantama', 'html_url': 'https://github.com/matteosantama', 'followers_url': 'https://api.github.com/users/matteosantama/followers', 'following_url': 'https://api.github.com/users/matteosantama/following{/other_user}', 'gists_url': 'https://api.github.com/users/matteosantama/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/matteosantama/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/matteosantama/subscriptions', 'organizations_url': 'https://api.github.com/users/matteosantama/orgs', 'repos_url': 'https://api.github.com/users/matteosantama/repos', 'events_url': 'https://api.github.com/users/matteosantama/events{/privacy}', 'received_events_url': 'https://api.github.com/users/matteosantama/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2021-11-30T23:42:53Z,2021-11-30T23:42:53Z,,CONTRIBUTOR,,"### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.


### Reproducible Example

```python
import pandas as pd

pd.__version__
>>> '1.3.4'

numbers = [1, 2, 3, 4]
colors = [""green"", ""red"", ""blue""]
index = pd.MultiIndex.from_product([numbers, colors], names=[""numbers"", ""colors""])
df = pd.DataFrame({""data"": range(len(numbers) * len(colors))}, index=index)

df.groupby(level=[""colors""]).mean()
>>>         data
colors      
blue     6.5
green    4.5
red      5.5

df.groupby(level=[""colors""]).ewm(span=2).mean()
>>>                            data
colors numbers colors          
blue   1       blue    2.000000
       2       blue    4.250000
       3       blue    6.846154
       4       blue    9.650000
green  1       green   0.000000
       2       green   2.250000
       3       green   4.846154
       4       green   7.650000
red    1       red     1.000000
       2       red     3.250000
       3       red     5.846154
       4       red     8.650000
```


### Issue Description

By adding an intermediary `.ewm()` step to the groupby operation, the resulting DataFrame has a duplicate index column.

### Expected Behavior

I would expect consistent behavior whether I apply a `.ewm` transformation or not.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.8.12.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.1.0
Version          : Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.4
numpy            : 1.20.0
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 56.0.0
Cython           : 0.29.24
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.4
html5lib         : None
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.30.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
fsspec           : 2021.11.1
fastparquet      : None
gcsfs            : None
matplotlib       : 3.5.0
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 5.0.0
pyxlsb           : None
s3fs             : 2021.11.1
scipy            : 1.7.3
sqlalchemy       : 1.4.27
tables           : None
tabulate         : 0.8.9
xarray           : 0.20.1
xlrd             : None
xlwt             : None
numba            : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44696/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44696/timeline,,,
7,https://api.github.com/repos/pandas-dev/pandas/issues/44694,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44694/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44694/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44694/events,https://github.com/pandas-dev/pandas/pull/44694,1067659198,PR_kwDOAA0YD84vNctn,44694,TST: read_csv raisin error with string dtype and parse dates,"{'login': 'phofl', 'id': 61934744, 'node_id': 'MDQ6VXNlcjYxOTM0NzQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/phofl', 'html_url': 'https://github.com/phofl', 'followers_url': 'https://api.github.com/users/phofl/followers', 'following_url': 'https://api.github.com/users/phofl/following{/other_user}', 'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions', 'organizations_url': 'https://api.github.com/users/phofl/orgs', 'repos_url': 'https://api.github.com/users/phofl/repos', 'events_url': 'https://api.github.com/users/phofl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/phofl/received_events', 'type': 'User', 'site_admin': False}","[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2ODU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing', 'name': 'Testing', 'color': 'C4A000', 'default': False, 'description': 'pandas testing functions or related to the test suite'}, {'id': 47229171, 'node_id': 'MDU6TGFiZWw0NzIyOTE3MQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20CSV', 'name': 'IO CSV', 'color': '5319e7', 'default': False, 'description': 'read_csv, to_csv'}]",open,False,,[],,0,2021-11-30T20:44:53Z,2021-11-30T20:45:02Z,,MEMBER,,"- [x] closes #34066
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them

","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44694/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44694/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/44694', 'html_url': 'https://github.com/pandas-dev/pandas/pull/44694', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/44694.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/44694.patch', 'merged_at': None}"
8,https://api.github.com/repos/pandas-dev/pandas/issues/44693,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44693/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44693/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44693/events,https://github.com/pandas-dev/pandas/issues/44693,1067622571,I_kwDOAA0YD84_oqCr,44693,BUG: dtypes cast when reading JSON,"{'login': 'ConstantinoSchillebeeckx', 'id': 8518288, 'node_id': 'MDQ6VXNlcjg1MTgyODg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8518288?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ConstantinoSchillebeeckx', 'html_url': 'https://github.com/ConstantinoSchillebeeckx', 'followers_url': 'https://api.github.com/users/ConstantinoSchillebeeckx/followers', 'following_url': 'https://api.github.com/users/ConstantinoSchillebeeckx/following{/other_user}', 'gists_url': 'https://api.github.com/users/ConstantinoSchillebeeckx/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ConstantinoSchillebeeckx/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ConstantinoSchillebeeckx/subscriptions', 'organizations_url': 'https://api.github.com/users/ConstantinoSchillebeeckx/orgs', 'repos_url': 'https://api.github.com/users/ConstantinoSchillebeeckx/repos', 'events_url': 'https://api.github.com/users/ConstantinoSchillebeeckx/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ConstantinoSchillebeeckx/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,2,2021-11-30T20:00:00Z,2021-12-01T13:51:44Z,,NONE,,"### 

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.
- [X] I have confirmed this bug exists on the master branch of pandas.


### Reproducible Example

```python
import pandas as pd
import json

# Correct behavior with pd.read_csv

csv_data = """"""
date,bool,good_str,good_int,good_float,mixed_types,int_w_missing,str_w_missing
2021-01-01,0,a,1,1.0,1,1,a
2021-01-01,1,b,2,2.2,b,,
""""""
    
with open(""foo.csv"", ""w"") as f:
    f.write(csv_data)

# this correctly raises ValueError: could not convert string to float: 'b'
df_csv = pd.read_csv(""foo.csv"", dtype={""int_w_missing"":""Int64"", ""mixed_types"": ""float""})

# ---------------

# Incorrect? behavior with pd.read_json

json_data = [
        {
            ""date"": ""2021-01-01"",
            ""good_int"": 5,
            ""int_w_missing"": 10,
            ""good_str"": ""114117967"",
            ""mixed_types"": ""455590""
        },
        {
            ""date"": ""2021-01-01"",
            ""good_int"": 5,
            ""good_str"": ""114011434"",
            ""mixed_types"": ""something""
        }
]


with open(""foo.json"", ""w"") as f:
    f.write(json.dumps(json_data))
    
# this does not raise anything
df_json = pd.read_json(""foo.json"", orient='records', dtype={""int_w_missing"":""Int64"", ""mixed_types"": ""float""})

# checking dtypes we see ""int_w_missing"" nor ""mixed_types"" were cast
df_json.dtypes
```


### Issue Description

Using `dtype` with `pd.read_json`:
1. does not raise raise a ValueError when casting something like the `str` ""something"" to a `float`
2. does not correctly cast to `Int64` when casting a `int` field with missing values

### Expected Behavior

1. raise a ValueError when casting something like the `str` ""something"" to a `float`
2. correctly cast to `Int64` when casting a `int` field with missing values

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.8.11.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.4
numpy            : 1.21.2
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.1.3
setuptools       : 57.4.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.27.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : None
odfpy            : None
openpyxl         : 3.0.8
pandas_gbq       : None
pyarrow          : 5.0.0
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44693/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44693/timeline,,,
9,https://api.github.com/repos/pandas-dev/pandas/issues/44692,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44692/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44692/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44692/events,https://github.com/pandas-dev/pandas/pull/44692,1067604921,PR_kwDOAA0YD84vNRj_,44692,API: value_counts consistently return int64 dtype,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2021-11-30T19:38:02Z,2021-12-01T13:57:31Z,,MEMBER,,"- [x] closes #44679
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44692/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44692/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/44692', 'html_url': 'https://github.com/pandas-dev/pandas/pull/44692', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/44692.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/44692.patch', 'merged_at': None}"
10,https://api.github.com/repos/pandas-dev/pandas/issues/44691,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44691/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44691/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44691/events,https://github.com/pandas-dev/pandas/pull/44691,1067603231,PR_kwDOAA0YD84vNROK,44691,REF: simplify Block.where (and subtle alignment bug),"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}","[{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2ODE=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Refactor', 'name': 'Refactor', 'color': 'FCE94F', 'default': False, 'description': 'Internal refactoring of code'}, {'id': 49094459, 'node_id': 'MDU6TGFiZWw0OTA5NDQ1OQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Internals', 'name': 'Internals', 'color': 'fbca04', 'default': False, 'description': 'Related to non-user accessible pandas implementation'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/86', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/86', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/86/labels', 'id': 6840253, 'node_id': 'MDk6TWlsZXN0b25lNjg0MDI1Mw==', 'number': 86, 'title': '1.4', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 80, 'closed_issues': 1345, 'state': 'open', 'created_at': '2021-06-09T18:28:42Z', 'updated_at': '2021-12-01T09:19:52Z', 'due_on': '2021-12-31T08:00:00Z', 'closed_at': None}",2,2021-11-30T19:35:59Z,2021-12-01T01:49:01Z,,MEMBER,,"- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

The alignment is not user-facing AFAICT, but comes up when trying to address #44597.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44691/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44691/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/44691', 'html_url': 'https://github.com/pandas-dev/pandas/pull/44691', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/44691.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/44691.patch', 'merged_at': None}"
11,https://api.github.com/repos/pandas-dev/pandas/issues/44690,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44690/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44690/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44690/events,https://github.com/pandas-dev/pandas/issues/44690,1067149753,I_kwDOAA0YD84_m2m5,44690,ENH: Add a `reset` parameter to `cumsum`,"{'login': 'JivanRoquet', 'id': 6452675, 'node_id': 'MDQ6VXNlcjY0NTI2NzU=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6452675?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/JivanRoquet', 'html_url': 'https://github.com/JivanRoquet', 'followers_url': 'https://api.github.com/users/JivanRoquet/followers', 'following_url': 'https://api.github.com/users/JivanRoquet/following{/other_user}', 'gists_url': 'https://api.github.com/users/JivanRoquet/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/JivanRoquet/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/JivanRoquet/subscriptions', 'organizations_url': 'https://api.github.com/users/JivanRoquet/orgs', 'repos_url': 'https://api.github.com/users/JivanRoquet/repos', 'events_url': 'https://api.github.com/users/JivanRoquet/events{/privacy}', 'received_events_url': 'https://api.github.com/users/JivanRoquet/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,3,2021-11-30T11:58:41Z,2021-11-30T12:37:34Z,,NONE,,"#### Is your feature request related to a problem?

There is a plethora of StackOverflow questions on how to reset the cumsum based on some criteria. The most common scenario seems to be to reset the cumsum on 0 or NaN values, so that it produces the following results (example with reset on NaN):

```
orig     cumsum
 1.0        1.0
 1.5        2.5
-2.0        0.5
 NaN        0.0
 1.0        1.0
-0.5        0.5
```

The problem is that there doesn't seem to be any standard way to do this, and the most commonly used methods are cumbersome and highly error-prone, despite the actual problem being conceptually simple (just reset the cumsum when encountering some criteria).

#### Describe the solution you'd like

Using a `reset` parameter could make resetting the cumsum as simple as:

```python
c = df['orig'].cumsum(reset=df['orig'].isnull())
```

Optionally, there could be a `reset_init` optional parameter which would be `0` by default, which would allow the cumsum to be set to `reset_init` value when encountering the reset condition.

#### API breaking implications

As this would be a new optional parameter (`None` by default), I don't see any potential API breaking.

#### Describe alternatives you've considered

The alternative is using a complicated series of unintuitive combinations of `cumsum` to get to the desired result.

An example of such convoluted way that is currently available is of the form:

```pyhon
v = pd.Series([1., 3., 1., np.nan, 1., 1., 1., 1., np.nan, 1.])
cumsum = v.cumsum().fillna(method='pad')
reset = -cumsum[v.isnull()].diff().fillna(cumsum)
result = v.where(v.notnull(), reset).cumsum()
```

Which is extremely hard to read and, again, makes a very complicated solution for what is conceptually a simple problem.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44690/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44690/timeline,,,
12,https://api.github.com/repos/pandas-dev/pandas/issues/44689,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44689/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44689/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44689/events,https://github.com/pandas-dev/pandas/issues/44689,1067142881,I_kwDOAA0YD84_m07h,44689,ENH: pandas.DataFrame.attrs,"{'login': 'shrutir21', 'id': 95286997, 'node_id': 'U_kgDOBa321Q', 'avatar_url': 'https://avatars.githubusercontent.com/u/95286997?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/shrutir21', 'html_url': 'https://github.com/shrutir21', 'followers_url': 'https://api.github.com/users/shrutir21/followers', 'following_url': 'https://api.github.com/users/shrutir21/following{/other_user}', 'gists_url': 'https://api.github.com/users/shrutir21/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/shrutir21/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/shrutir21/subscriptions', 'organizations_url': 'https://api.github.com/users/shrutir21/orgs', 'repos_url': 'https://api.github.com/users/shrutir21/repos', 'events_url': 'https://api.github.com/users/shrutir21/events{/privacy}', 'received_events_url': 'https://api.github.com/users/shrutir21/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2021-11-30T11:51:05Z,2021-11-30T12:42:43Z,,NONE,,"#### Is your feature request related to a problem?

I am working on a large project which involves the use of pandas data frames throughout. Due to this, I need to be able to assign string names to data frames and call upon them (and ideally other attributes too which depend on the DataFrame in question e.g. colour etc.). For now I have been able to do so using 'pandas.DataFrame.attrs' which has worked perfectly. However, on the documentation page it says that this may be subject to change without prior warning and therefore I am hesitant to use it in such a large project as if it does change, it will cause major issues.

#### Describe the solution you'd like

I was therefore wondering if there was the possibility of making this a permanent feature of pandas as it (extremely usefully) allows attributes to be assigned to data frames and called upon easily when the DataFrame in question is being 'used' per say.

#### Describe alternatives you've considered

 Alternatives could be if there is another, more 'secure' way to replicate what 'pandas.DataFrame.attrs' does or even the possibility of creating a way to allow easier assignment of string names (and other attributes) to data frames.

Any help/insight is greatly appreciated. 

EDIT: Assigning DataFrame string names and attributes is also a common request on StackOverflow and as far as I have seen, there are no 'easy' or simple ways around this other than the 'attrs' method above so I believe this would be an extremely helpful and widely used feature of pandas if it were to be made available permanently. 

Thank you.

```
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44689/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44689/timeline,,,
13,https://api.github.com/repos/pandas-dev/pandas/issues/44688,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44688/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44688/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44688/events,https://github.com/pandas-dev/pandas/pull/44688,1067002088,PR_kwDOAA0YD84vLSzN,44688,ENH: Add indexing syntax to GroupBy.nth(),"{'login': 'johnzangwill', 'id': 8927258, 'node_id': 'MDQ6VXNlcjg5MjcyNTg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8927258?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/johnzangwill', 'html_url': 'https://github.com/johnzangwill', 'followers_url': 'https://api.github.com/users/johnzangwill/followers', 'following_url': 'https://api.github.com/users/johnzangwill/following{/other_user}', 'gists_url': 'https://api.github.com/users/johnzangwill/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/johnzangwill/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/johnzangwill/subscriptions', 'organizations_url': 'https://api.github.com/users/johnzangwill/orgs', 'repos_url': 'https://api.github.com/users/johnzangwill/repos', 'events_url': 'https://api.github.com/users/johnzangwill/events{/privacy}', 'received_events_url': 'https://api.github.com/users/johnzangwill/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2021-11-30T09:33:26Z,2021-11-30T14:14:14Z,,CONTRIBUTOR,,"- [x] closes #44589
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

Add index notation to nth for lists of integers and slices","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44688/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44688/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/44688', 'html_url': 'https://github.com/pandas-dev/pandas/pull/44688', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/44688.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/44688.patch', 'merged_at': None}"
14,https://api.github.com/repos/pandas-dev/pandas/issues/44687,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44687/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44687/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44687/events,https://github.com/pandas-dev/pandas/issues/44687,1066991344,I_kwDOAA0YD84_mP7w,44687,BUG: ,"{'login': 'Iqigai', 'id': 80190909, 'node_id': 'MDQ6VXNlcjgwMTkwOTA5', 'avatar_url': 'https://avatars.githubusercontent.com/u/80190909?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Iqigai', 'html_url': 'https://github.com/Iqigai', 'followers_url': 'https://api.github.com/users/Iqigai/followers', 'following_url': 'https://api.github.com/users/Iqigai/following{/other_user}', 'gists_url': 'https://api.github.com/users/Iqigai/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Iqigai/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Iqigai/subscriptions', 'organizations_url': 'https://api.github.com/users/Iqigai/orgs', 'repos_url': 'https://api.github.com/users/Iqigai/repos', 'events_url': 'https://api.github.com/users/Iqigai/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Iqigai/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2021-11-30T09:23:14Z,2021-12-01T05:50:23Z,,NONE,,"### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.


### Reproducible Example

```python
df = pd.DataFrame({'A': [1] * 5 + [0]*5})
win_size = 4
df['left'] = df[A'].rolling(win_size, closed='left').sum()
df['right'] = df['A'].rolling(win_size, closed='right').sum()
df['both'] = df['A'].rolling(win_size, closed='both').sum()
df['neither'] = df[AB'].rolling(win_size, closed='neither').sum()
df
Out[6]: 
    A  left  right  both  neither
0  1   NaN    NaN   NaN      NaN
1  1   NaN    NaN   NaN      NaN
2  1   NaN    NaN   NaN      NaN
3  1   NaN    NaN   NaN      NaN
4  1   NaN    5.0   5.0      NaN
5  0   5.0    4.0   5.0      NaN
6  0   4.0    3.0   4.0      NaN
7  0   3.0    2.0   3.0      NaN
8  0   2.0    1.0   2.0      NaN
9  0   1.0    0.0   1.0      NaN

### Issue Description
There seem to be some inconsistencies in the behavior of the rolling function related to the parameter 'closed'. Different options were tested and assigned to a different column in the toy example above.
First, when we use 'neither' it returns NaNs as per the 'neither' column.
Second when we use 'right' or 'left', the count reaches the maximum window size, which is not coherent. If we exclude one of the endpoints the maximum should be win_size - 1 since one of the end points is excluded. What more, if we in the case of closed='both;, we even get a count of elements greater than the window size, in this case 5, vs 4. It seems that the closed parameter affects the window position and shape rather than just the inclusion of the endpoints. The exact behavior should be better described if this is not a bug.


### Expected Behavior

1- Using 'neither', should yield the same result as 'left' minus 1. Actually this parameter value is redundant since the result could be obtained by taking a window size one unit smaller and closed set to 'left'.
2- Using 'left' or 'right' should exclude from the calculation one of the endpoints and never take the whole window for calculation
3- Using 'both', should use a window, exactly the same size as the parameter 'window', inclusive of the current row.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.9.7.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19043
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_Canada.1252
pandas           : 1.3.4
numpy            : 1.19.5
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.3.1
setuptools       : 58.2.0
Cython           : 0.29.24
pytest           : 6.2.5
hypothesis       : 6.23.2
sphinx           : 4.0.2
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.29.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 4.0.1
pyxlsb           : None
s3fs             : None
scipy            : 1.7.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.54.1

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44687/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44687/timeline,,,
15,https://api.github.com/repos/pandas-dev/pandas/issues/44685,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44685/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44685/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44685/events,https://github.com/pandas-dev/pandas/pull/44685,1066813096,PR_kwDOAA0YD84vKr5O,44685,TST: fix Nullable xfails,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}","[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2ODU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing', 'name': 'Testing', 'color': 'C4A000', 'default': False, 'description': 'pandas testing functions or related to the test suite'}, {'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQwNDUyMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Dtype%20Conversions', 'name': 'Dtype Conversions', 'color': 'e102d8', 'default': False, 'description': 'Unexpected or buggy dtype conversions'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/86', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/86', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/86/labels', 'id': 6840253, 'node_id': 'MDk6TWlsZXN0b25lNjg0MDI1Mw==', 'number': 86, 'title': '1.4', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 80, 'closed_issues': 1345, 'state': 'open', 'created_at': '2021-06-09T18:28:42Z', 'updated_at': '2021-12-01T09:19:52Z', 'due_on': '2021-12-31T08:00:00Z', 'closed_at': None}",4,2021-11-30T05:32:17Z,2021-12-01T02:29:11Z,,MEMBER,,"- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44685/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44685/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/44685', 'html_url': 'https://github.com/pandas-dev/pandas/pull/44685', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/44685.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/44685.patch', 'merged_at': None}"
16,https://api.github.com/repos/pandas-dev/pandas/issues/44684,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44684/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44684/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44684/events,https://github.com/pandas-dev/pandas/issues/44684,1066791744,I_kwDOAA0YD84_lfNA,44684,BUG: the precision of big integer in read_json,"{'login': 'bytedynamic', 'id': 54274219, 'node_id': 'MDQ6VXNlcjU0Mjc0MjE5', 'avatar_url': 'https://avatars.githubusercontent.com/u/54274219?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/bytedynamic', 'html_url': 'https://github.com/bytedynamic', 'followers_url': 'https://api.github.com/users/bytedynamic/followers', 'following_url': 'https://api.github.com/users/bytedynamic/following{/other_user}', 'gists_url': 'https://api.github.com/users/bytedynamic/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/bytedynamic/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/bytedynamic/subscriptions', 'organizations_url': 'https://api.github.com/users/bytedynamic/orgs', 'repos_url': 'https://api.github.com/users/bytedynamic/repos', 'events_url': 'https://api.github.com/users/bytedynamic/events{/privacy}', 'received_events_url': 'https://api.github.com/users/bytedynamic/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 49379259, 'node_id': 'MDU6TGFiZWw0OTM3OTI1OQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20JSON', 'name': 'IO JSON', 'color': '207de5', 'default': False, 'description': 'read_json, to_json, json_normalize'}]",open,False,,[],,2,2021-11-30T04:56:24Z,2021-12-01T05:08:25Z,,NONE,,"### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the master branch of pandas.


### Reproducible Example

```python
import pandas as pd

jsn = '[{""NO"": ""202101010000000003"", ""NAME"": ""A""}, {""NO"": ""202101010000000013"", ""NAME"": ""B""}, {""NO"": ""202101010000000023"", ""NAME"": ""C""}]'


df1 = pd.read_json(jsn)
print(df1)
```


### Issue Description

I have a json file, and column ""NO"" is a big integer.
I use pd.read_json() read the json file, however, the  value of column ""NO"" in the DataFrame is not exactly equal to the value in json file. DataFrame as follows:

| | NO | NAME
-- | -- | --
0 | 202101010000000000 | A
1 | 202101010000000000 | B
2 | 202101010000000032 | C

and I use df.info(), which shows the dtype of Column ""NO"" is int64.
```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   NO      3 non-null      int64 
 1   NAME    3 non-null      object
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes
```

It's really strange. The range of int64 is -9223372036854775808 ~ 9223372036854775807 and 202101010000000003 is in the range.

### Expected Behavior

| | NO | NAME
-- | -- | --
0 | 202101010000000003 | A
1 | 202101010000000013 | B
2 | 202101010000000023 | C

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
python           : 3.8.8.final.0
pandas           : 1.3.4
numpy            : 1.21.4
</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44684/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44684/timeline,,,
17,https://api.github.com/repos/pandas-dev/pandas/issues/44682,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44682/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44682/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44682/events,https://github.com/pandas-dev/pandas/pull/44682,1066707884,PR_kwDOAA0YD84vKWXh,44682,CI: Try to not auto-cancel on master,"{'login': 'lithomas1', 'id': 47963215, 'node_id': 'MDQ6VXNlcjQ3OTYzMjE1', 'avatar_url': 'https://avatars.githubusercontent.com/u/47963215?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lithomas1', 'html_url': 'https://github.com/lithomas1', 'followers_url': 'https://api.github.com/users/lithomas1/followers', 'following_url': 'https://api.github.com/users/lithomas1/following{/other_user}', 'gists_url': 'https://api.github.com/users/lithomas1/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lithomas1/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lithomas1/subscriptions', 'organizations_url': 'https://api.github.com/users/lithomas1/orgs', 'repos_url': 'https://api.github.com/users/lithomas1/repos', 'events_url': 'https://api.github.com/users/lithomas1/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lithomas1/received_events', 'type': 'User', 'site_admin': False}","[{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3MDYwMA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/CI', 'name': 'CI', 'color': 'a2bca7', 'default': False, 'description': 'Continuous Integration'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/86', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/86', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/86/labels', 'id': 6840253, 'node_id': 'MDk6TWlsZXN0b25lNjg0MDI1Mw==', 'number': 86, 'title': '1.4', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 80, 'closed_issues': 1345, 'state': 'open', 'created_at': '2021-06-09T18:28:42Z', 'updated_at': '2021-12-01T09:19:52Z', 'due_on': '2021-12-31T08:00:00Z', 'closed_at': None}",2,2021-11-30T02:17:49Z,2021-12-01T03:57:23Z,,MEMBER,,"- [ ] closes #42076
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

Seems to work. Let's try this again.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44682/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44682/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/44682', 'html_url': 'https://github.com/pandas-dev/pandas/pull/44682', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/44682.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/44682.patch', 'merged_at': None}"
18,https://api.github.com/repos/pandas-dev/pandas/issues/44681,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44681/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44681/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44681/events,https://github.com/pandas-dev/pandas/pull/44681,1066703171,PR_kwDOAA0YD84vKVbA,44681,REF: hold PeriodArray in NDArrayBackedExtensionBlock,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2021-11-30T02:10:05Z,2021-11-30T02:10:05Z,,MEMBER,,"- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

After this, Categorical will be the only NDArrayBackedExtensionArray not held in NDarrayBackedExtensionBlock.

(this also fixes a Series.where bug for PeriodDtype, the general fix (and tests) are blocked by #44514)","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44681/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44681/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/44681', 'html_url': 'https://github.com/pandas-dev/pandas/pull/44681', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/44681.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/44681.patch', 'merged_at': None}"
19,https://api.github.com/repos/pandas-dev/pandas/issues/44680,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44680/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44680/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44680/events,https://github.com/pandas-dev/pandas/pull/44680,1066666530,PR_kwDOAA0YD84vKODL,44680,44414 data frame attributes not propagating with astype,"{'login': 'skwirskj', 'id': 47086561, 'node_id': 'MDQ6VXNlcjQ3MDg2NTYx', 'avatar_url': 'https://avatars.githubusercontent.com/u/47086561?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/skwirskj', 'html_url': 'https://github.com/skwirskj', 'followers_url': 'https://api.github.com/users/skwirskj/followers', 'following_url': 'https://api.github.com/users/skwirskj/following{/other_user}', 'gists_url': 'https://api.github.com/users/skwirskj/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/skwirskj/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/skwirskj/subscriptions', 'organizations_url': 'https://api.github.com/users/skwirskj/orgs', 'repos_url': 'https://api.github.com/users/skwirskj/repos', 'events_url': 'https://api.github.com/users/skwirskj/events{/privacy}', 'received_events_url': 'https://api.github.com/users/skwirskj/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,1,2021-11-30T00:59:37Z,2021-11-30T23:11:59Z,,NONE,,"- [x] closes #44414 
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44680/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44680/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/44680', 'html_url': 'https://github.com/pandas-dev/pandas/pull/44680', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/44680.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/44680.patch', 'merged_at': None}"
20,https://api.github.com/repos/pandas-dev/pandas/issues/44679,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44679/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44679/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44679/events,https://github.com/pandas-dev/pandas/issues/44679,1066653886,I_kwDOAA0YD84_k9i-,44679,API: value_counts with nullable dtype should return np.int64 like everything else,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}","[{'id': 57296398, 'node_id': 'MDU6TGFiZWw1NzI5NjM5OA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Algos', 'name': 'Algos', 'color': 'eb6420', 'default': False, 'description': 'Non-arithmetic algos: value_counts, factorize, sorting, isin, clip, shift, diff'}, {'id': 1741841389, 'node_id': 'MDU6TGFiZWwxNzQxODQxMzg5', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/API%20-%20Consistency', 'name': 'API - Consistency', 'color': 'b60205', 'default': False, 'description': 'Internal Consistency of API/Behavior'}, {'id': 1817503692, 'node_id': 'MDU6TGFiZWwxODE3NTAzNjky', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/NA%20-%20MaskedArrays', 'name': 'NA - MaskedArrays', 'color': '8cc645', 'default': False, 'description': 'Related to pd.NA and nullable extension arrays'}]",open,False,,[],,1,2021-11-30T00:39:10Z,2021-11-30T13:09:46Z,,MEMBER,,"ATM these are special-cased to return Int64 (i.e. nullable) instead of np.int64.  But the result of value_counts will never have any NAs, so there is no benefit.  It complicates the code, complicates the API, and prevents us from sharing tests.

These should return np.int64 dtype like everything else. 
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44679/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44679/timeline,,,
21,https://api.github.com/repos/pandas-dev/pandas/issues/44678,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44678/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44678/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44678/events,https://github.com/pandas-dev/pandas/pull/44678,1066623923,PR_kwDOAA0YD84vKE3z,44678,Type read_fwf,"{'login': 'phofl', 'id': 61934744, 'node_id': 'MDQ6VXNlcjYxOTM0NzQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/phofl', 'html_url': 'https://github.com/phofl', 'followers_url': 'https://api.github.com/users/phofl/followers', 'following_url': 'https://api.github.com/users/phofl/following{/other_user}', 'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions', 'organizations_url': 'https://api.github.com/users/phofl/orgs', 'repos_url': 'https://api.github.com/users/phofl/repos', 'events_url': 'https://api.github.com/users/phofl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/phofl/received_events', 'type': 'User', 'site_admin': False}","[{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMjgwOTg4NDI3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Typing', 'name': 'Typing', 'color': 'ea91a4', 'default': False, 'description': 'type annotations, mypy/pyright type checking'}, {'id': 1728902385, 'node_id': 'MDU6TGFiZWwxNzI4OTAyMzg1', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20Fixed%20Width', 'name': 'IO Fixed Width', 'color': 'e99695', 'default': False, 'description': 'read_fwf'}]",open,False,,[],,0,2021-11-29T23:56:21Z,2021-12-01T01:38:25Z,,MEMBER,,"- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44678/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44678/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/44678', 'html_url': 'https://github.com/pandas-dev/pandas/pull/44678', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/44678.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/44678.patch', 'merged_at': None}"
22,https://api.github.com/repos/pandas-dev/pandas/issues/44677,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44677/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44677/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44677/events,https://github.com/pandas-dev/pandas/pull/44677,1066562867,PR_kwDOAA0YD84vJ4UN,44677,Typ parts of c parser,"{'login': 'phofl', 'id': 61934744, 'node_id': 'MDQ6VXNlcjYxOTM0NzQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/phofl', 'html_url': 'https://github.com/phofl', 'followers_url': 'https://api.github.com/users/phofl/followers', 'following_url': 'https://api.github.com/users/phofl/following{/other_user}', 'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions', 'organizations_url': 'https://api.github.com/users/phofl/orgs', 'repos_url': 'https://api.github.com/users/phofl/repos', 'events_url': 'https://api.github.com/users/phofl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/phofl/received_events', 'type': 'User', 'site_admin': False}","[{'id': 47229171, 'node_id': 'MDU6TGFiZWw0NzIyOTE3MQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20CSV', 'name': 'IO CSV', 'color': '5319e7', 'default': False, 'description': 'read_csv, to_csv'}, {'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMjgwOTg4NDI3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Typing', 'name': 'Typing', 'color': 'ea91a4', 'default': False, 'description': 'type annotations, mypy/pyright type checking'}]",open,False,,[],,0,2021-11-29T22:20:10Z,2021-12-01T02:00:14Z,,MEMBER,,"- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them

","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44677/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44677/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/44677', 'html_url': 'https://github.com/pandas-dev/pandas/pull/44677', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/44677.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/44677.patch', 'merged_at': None}"
23,https://api.github.com/repos/pandas-dev/pandas/issues/44676,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44676/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44676/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44676/events,https://github.com/pandas-dev/pandas/pull/44676,1066538958,PR_kwDOAA0YD84vJzXj,44676,CLN: helper attribute to check for ArrayManager,"{'login': 'jorisvandenbossche', 'id': 1020496, 'node_id': 'MDQ6VXNlcjEwMjA0OTY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1020496?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jorisvandenbossche', 'html_url': 'https://github.com/jorisvandenbossche', 'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers', 'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}', 'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions', 'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs', 'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos', 'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events', 'type': 'User', 'site_admin': False}","[{'id': 3165546917, 'node_id': 'MDU6TGFiZWwzMTY1NTQ2OTE3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/ArrayManager', 'name': 'ArrayManager', 'color': '1d76db', 'default': False, 'description': ''}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/86', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/86', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/86/labels', 'id': 6840253, 'node_id': 'MDk6TWlsZXN0b25lNjg0MDI1Mw==', 'number': 86, 'title': '1.4', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 80, 'closed_issues': 1345, 'state': 'open', 'created_at': '2021-06-09T18:28:42Z', 'updated_at': '2021-12-01T09:19:52Z', 'due_on': '2021-12-31T08:00:00Z', 'closed_at': None}",4,2021-11-29T21:50:20Z,2021-12-01T16:38:29Z,,MEMBER,,xref https://github.com/pandas-dev/pandas/pull/41878#discussion_r758514585,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44676/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44676/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/44676', 'html_url': 'https://github.com/pandas-dev/pandas/pull/44676', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/44676.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/44676.patch', 'merged_at': None}"
24,https://api.github.com/repos/pandas-dev/pandas/issues/44672,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44672/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44672/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44672/events,https://github.com/pandas-dev/pandas/pull/44672,1066108438,PR_kwDOAA0YD84vIbe-,44672,Deprecate mapper argument in rename,"{'login': 'Varun270', 'id': 75975268, 'node_id': 'MDQ6VXNlcjc1OTc1MjY4', 'avatar_url': 'https://avatars.githubusercontent.com/u/75975268?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Varun270', 'html_url': 'https://github.com/Varun270', 'followers_url': 'https://api.github.com/users/Varun270/followers', 'following_url': 'https://api.github.com/users/Varun270/following{/other_user}', 'gists_url': 'https://api.github.com/users/Varun270/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Varun270/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Varun270/subscriptions', 'organizations_url': 'https://api.github.com/users/Varun270/orgs', 'repos_url': 'https://api.github.com/users/Varun270/repos', 'events_url': 'https://api.github.com/users/Varun270/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Varun270/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,4,2021-11-29T14:30:11Z,2021-11-30T14:54:18Z,,CONTRIBUTOR,,"- [x] supposed fix #44627
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44672/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44672/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/44672', 'html_url': 'https://github.com/pandas-dev/pandas/pull/44672', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/44672.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/44672.patch', 'merged_at': None}"
25,https://api.github.com/repos/pandas-dev/pandas/issues/44671,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44671/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44671/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44671/events,https://github.com/pandas-dev/pandas/issues/44671,1066096407,I_kwDOAA0YD84_i1cX,44671,ENH: Pairwise method or symmetric keyword in DataFrame.corr,"{'login': 'maurosilber', 'id': 9124827, 'node_id': 'MDQ6VXNlcjkxMjQ4Mjc=', 'avatar_url': 'https://avatars.githubusercontent.com/u/9124827?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/maurosilber', 'html_url': 'https://github.com/maurosilber', 'followers_url': 'https://api.github.com/users/maurosilber/followers', 'following_url': 'https://api.github.com/users/maurosilber/following{/other_user}', 'gists_url': 'https://api.github.com/users/maurosilber/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/maurosilber/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/maurosilber/subscriptions', 'organizations_url': 'https://api.github.com/users/maurosilber/orgs', 'repos_url': 'https://api.github.com/users/maurosilber/repos', 'events_url': 'https://api.github.com/users/maurosilber/events{/privacy}', 'received_events_url': 'https://api.github.com/users/maurosilber/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}, {'id': 2365504893, 'node_id': 'MDU6TGFiZWwyMzY1NTA0ODkz', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Closing%20Candidate', 'name': 'Closing Candidate', 'color': 'be21f2', 'default': False, 'description': 'May be closeable, needs more eyeballs'}]",open,False,,[],,1,2021-11-29T14:19:41Z,2021-11-29T15:34:17Z,,NONE,,"#### Is your feature request related to a problem?

I wish I could use pandas to do pairwise computations.

#### Describe the solution you'd like

The [`DataFrame.corr`](https://github.com/pandas-dev/pandas/blob/c58d8ee6e93fc1ba7aa4a40dc71488cc9807ed43/pandas/core/frame.py#L9526-L9545) method accepts a callable to compute a user-specified correlation function. Its docstring says:

> callable: callable with input two 1d ndarrays returning a float. Note that the returned matrix from corr have 1 along the diagonals and will be symmetric of the callable's behavior.

I'd like to compute pairwise calculations which are not symmetric. I can think of two possible solutions:

1. Add a `symmetric` keyword-only argument, changing the signature to:

```python
def corr(
        self,
        method: str | Callable[[np.ndarray, np.ndarray], float] = ""pearson"",
        min_periods: int = 1,
        *,
        symmetric=True,
    ) -> DataFrame:
```

It keeps the current behaviour by default, but allows asymmetric callables to be computed. It could also change the behaviour when computing the diagonals, which are now set to 1, independently of the function provided.

2. Add a new pairwise method.

#### API breaking implications

The first option shouldn't change the API, as it is adding a keyword-only argument which keeps current behaviour as default.

The second option might not be backwards-compatible with code where columns are named `pairwise` and called via attribute access.

#### Additional context

A similar issue was raised here: https://github.com/pandas-dev/pandas/issues/25726","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44671/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44671/timeline,,,
26,https://api.github.com/repos/pandas-dev/pandas/issues/44670,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44670/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44670/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44670/events,https://github.com/pandas-dev/pandas/issues/44670,1065985834,I_kwDOAA0YD84_iacq,44670,BUG: Pandas plot does not accept Columns for color keyword,"{'login': 'mosc9575', 'id': 68053396, 'node_id': 'MDQ6VXNlcjY4MDUzMzk2', 'avatar_url': 'https://avatars.githubusercontent.com/u/68053396?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mosc9575', 'html_url': 'https://github.com/mosc9575', 'followers_url': 'https://api.github.com/users/mosc9575/followers', 'following_url': 'https://api.github.com/users/mosc9575/following{/other_user}', 'gists_url': 'https://api.github.com/users/mosc9575/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mosc9575/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mosc9575/subscriptions', 'organizations_url': 'https://api.github.com/users/mosc9575/orgs', 'repos_url': 'https://api.github.com/users/mosc9575/repos', 'events_url': 'https://api.github.com/users/mosc9575/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mosc9575/received_events', 'type': 'User', 'site_admin': False}","[{'id': 2413328, 'node_id': 'MDU6TGFiZWwyNDEzMzI4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Visualization', 'name': 'Visualization', 'color': '8AE234', 'default': False, 'description': None}, {'id': 1741841389, 'node_id': 'MDU6TGFiZWwxNzQxODQxMzg5', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/API%20-%20Consistency', 'name': 'API - Consistency', 'color': 'b60205', 'default': False, 'description': 'Internal Consistency of API/Behavior'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/32', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels', 'id': 933188, 'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4', 'number': 32, 'title': 'Contributions Welcome', 'description': 'Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 1044, 'closed_issues': 789, 'state': 'open', 'created_at': '2015-01-13T10:53:19Z', 'updated_at': '2021-12-01T01:35:27Z', 'due_on': None, 'closed_at': None}",6,2021-11-29T12:34:05Z,2021-11-29T22:41:32Z,,NONE,,"### 

- [ ] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.


### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({
 'A': {1: 6, 2: 2, 3: 1, 4: 8, 5: 6},
 'B': {1: 2, 2: 10, 3: 3, 4: 1, 5: 1},
 'pos': {1: 1, 2: 2, 3: 4, 4: 1, 5: 1},
 'color': {1: 'red', 2: 'blue', 3: 'green', 4: 'red', 5: 'red'}
})

# df >>>
#    A   B  color
# 1  6   2    red
# 2  2  10   blue
# 3  1   3  green
# 4  8   1    red
# 5  6   1    red


df.plot(x='A', y='B', kind='scatter', color=df['color'].values)
# df.plot(x='A', y='B', kind='scatter', color='color')
```


### Issue Description

I tried to plot a scatterplot with different groups, with one color for each group. I thought is is enought to pass the name of the column to the color-keyword, but this throws an error:

`ValueError: 'c' argument must be a color, a sequence of colors, or a sequence of numbers, not ['color']`

### Expected Behavior

I expect this figure, which was generated using the commented line

`s.plot(x='A', y='B', kind='scatter', color=s['color'].values)`

![grafik](https://user-images.githubusercontent.com/68053396/143868392-11e5de24-d1a7-412d-9404-38a0b2b5afc6.png)


### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.0-8-amd64
Version          : #1 SMP Debian 5.10.46-4 (2021-08-03)
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.4
numpy            : 1.20.3
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.24
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.28.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 2021.09.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : 1.4.23
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.54.0
1
​

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44670/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44670/timeline,,,
27,https://api.github.com/repos/pandas-dev/pandas/issues/44669,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44669/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44669/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44669/events,https://github.com/pandas-dev/pandas/pull/44669,1065872778,PR_kwDOAA0YD84vHqCG,44669,BUG: Fix setitem with 1d matrix,"{'login': 'ivirshup', 'id': 8238804, 'node_id': 'MDQ6VXNlcjgyMzg4MDQ=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8238804?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ivirshup', 'html_url': 'https://github.com/ivirshup', 'followers_url': 'https://api.github.com/users/ivirshup/followers', 'following_url': 'https://api.github.com/users/ivirshup/following{/other_user}', 'gists_url': 'https://api.github.com/users/ivirshup/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ivirshup/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ivirshup/subscriptions', 'organizations_url': 'https://api.github.com/users/ivirshup/orgs', 'repos_url': 'https://api.github.com/users/ivirshup/repos', 'events_url': 'https://api.github.com/users/ivirshup/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ivirshup/received_events', 'type': 'User', 'site_admin': False}","[{'id': 1465286368, 'node_id': 'MDU6TGFiZWwxNDY1Mjg2MzY4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Constructors', 'name': 'Constructors', 'color': 'd4c5f9', 'default': False, 'description': 'Series/DataFrame/Index/pd.array Constructors'}]",open,False,,[],,1,2021-11-29T10:34:40Z,2021-12-01T17:42:47Z,,CONTRIBUTOR,,"- [x] closes #42376
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

Fixes the case `df[""mean""] = sparse.random(100, 10).mean(axis=1)` assigning a broken column.

Wasn't sure where the test should go, I feel like there must be a test for `x = np.ones((10, 1)); df[""x""] = x` somewhere.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44669/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44669/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/44669', 'html_url': 'https://github.com/pandas-dev/pandas/pull/44669', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/44669.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/44669.patch', 'merged_at': None}"
28,https://api.github.com/repos/pandas-dev/pandas/issues/44666,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44666/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44666/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44666/events,https://github.com/pandas-dev/pandas/pull/44666,1065706845,PR_kwDOAA0YD84vHHuT,44666,PERF: passthrough mask to take_1d if already known,"{'login': 'jorisvandenbossche', 'id': 1020496, 'node_id': 'MDQ6VXNlcjEwMjA0OTY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1020496?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jorisvandenbossche', 'html_url': 'https://github.com/jorisvandenbossche', 'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers', 'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}', 'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions', 'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs', 'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos', 'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events', 'type': 'User', 'site_admin': False}","[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1MzEx', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Performance', 'name': 'Performance', 'color': 'a10c02', 'default': False, 'description': 'Memory or execution speed performance'}, {'id': 3165546917, 'node_id': 'MDU6TGFiZWwzMTY1NTQ2OTE3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/ArrayManager', 'name': 'ArrayManager', 'color': '1d76db', 'default': False, 'description': ''}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/86', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/86', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/86/labels', 'id': 6840253, 'node_id': 'MDk6TWlsZXN0b25lNjg0MDI1Mw==', 'number': 86, 'title': '1.4', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 80, 'closed_issues': 1345, 'state': 'open', 'created_at': '2021-06-09T18:28:42Z', 'updated_at': '2021-12-01T09:19:52Z', 'due_on': '2021-12-31T08:00:00Z', 'closed_at': None}",3,2021-11-29T07:40:44Z,2021-11-29T21:17:17Z,,MEMBER,,"In `take_1d` (if `allow_fill=True`), the mask gets calculated based one `indexer == -1`. But in the cases where this function is used, we either actually already calculated this mask in advance, or can calculate it once instead of multiple times again in `take_1d` (repeated calls with the same mask), which improves the performance in both cases.

Showing with two benchmarks where ArrayManager was quite a bit slower because of this:

`Reindex.time_reindex_upcast` benchmark:

```python
import numpy as np
import pandas as pd

N = 10 ** 3
df2 = pd.DataFrame(
    {
        c: {
            0: np.random.randint(0, 2, N).astype(np.bool_),
            1: np.random.randint(0, N, N).astype(np.int16),
            2: np.random.randint(0, N, N).astype(np.int32),
            3: np.random.randint(0, N, N).astype(np.int64),
        }[np.random.randint(0, 4)]
        for c in range(N)
    }
)
idx2 = np.random.permutation(range(1200))

df2_am = df2._as_manager(""array"").copy()


In [3]: %timeit df2_am.reindex(idx2)
16.7 ms ± 1.72 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)  # <-- master
9.73 ms ± 1.65 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)  # <-- PR
```


`Unstack.time_without_last_row` benchmark:

```python
import numpy as np
import pandas as pd

dtype = 'int'
m = 100
n = 1000

levels = np.arange(m)
index = pd.MultiIndex.from_product([levels] * 2)
columns = np.arange(n)
values = np.arange(m * m * n).reshape(m * m, n)

df = pd.DataFrame(values, index, columns)
df2 = df.iloc[:-1]
df2_am = df2._as_manager(""array"").copy()

In [3]: %timeit df2_am.unstack()
594 ms ± 8.33 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)  # <-- master
183 ms ± 21.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)  # <-- PR
```
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44666/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44666/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/44666', 'html_url': 'https://github.com/pandas-dev/pandas/pull/44666', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/44666.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/44666.patch', 'merged_at': None}"
29,https://api.github.com/repos/pandas-dev/pandas/issues/44664,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/44664/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/44664/comments,https://api.github.com/repos/pandas-dev/pandas/issues/44664/events,https://github.com/pandas-dev/pandas/pull/44664,1065576873,PR_kwDOAA0YD84vGtCj,44664,TYP: changed variable cat_array to cat_array_list in dtypes.py and arr_list in categorical.py,"{'login': 'nickleus27', 'id': 44080390, 'node_id': 'MDQ6VXNlcjQ0MDgwMzkw', 'avatar_url': 'https://avatars.githubusercontent.com/u/44080390?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/nickleus27', 'html_url': 'https://github.com/nickleus27', 'followers_url': 'https://api.github.com/users/nickleus27/followers', 'following_url': 'https://api.github.com/users/nickleus27/following{/other_user}', 'gists_url': 'https://api.github.com/users/nickleus27/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/nickleus27/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/nickleus27/subscriptions', 'organizations_url': 'https://api.github.com/users/nickleus27/orgs', 'repos_url': 'https://api.github.com/users/nickleus27/repos', 'events_url': 'https://api.github.com/users/nickleus27/events{/privacy}', 'received_events_url': 'https://api.github.com/users/nickleus27/received_events', 'type': 'User', 'site_admin': False}","[{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMjgwOTg4NDI3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Typing', 'name': 'Typing', 'color': 'ea91a4', 'default': False, 'description': 'type annotations, mypy/pyright type checking'}]",open,False,,[],,2,2021-11-29T03:50:38Z,2021-12-01T06:34:35Z,,CONTRIBUTOR,,"xref #37715

My apologies, I pushed hastily on my previous branch assign_err and did not check the diff of the files i was pushing. I accidentally pulled when i should have merged and I pushed a bunch of other peoples commits.  These are my previous changes.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/44664/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/44664/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/44664', 'html_url': 'https://github.com/pandas-dev/pandas/pull/44664', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/44664.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/44664.patch', 'merged_at': None}"
